Repository lucc/khard, pull requests merged in 2019-10, with the labels that each got.

#226 Use dict internally for fields with ABLABEL
  khard/carddav_object.py
  khard/helpers.py
  test/test_vcard_wrapper.py
  test/test_yaml.py
Labels: enhancement

#227 Force strings that look like yaml mapping values to be displayed as multiline strings
  khard/helpers.py
  test/test_helpers.py
  test/test_yaml.py
Labels: bug

#229 More documentation stuff
  .gitignore
  CONTRIBUTING.rst
  README.rst
  doc/Makefile
  doc/source/commandline.rst
  doc/source/contributing.rst
  doc/source/examples/khard.conf.example
  doc/source/index.rst
  doc/source/man/khard.conf.rst
  doc/source/man/khard.rst
  doc/source/scripting.rst
  misc/khard/template_for_contact_creation.yaml
Labels: docs, enhancement
